# Generated by Django 4.1.7 on 2023-03-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='measure',
            field=models.CharField(choices=[('kg', 'kilo'), ('g', 'gramm'), ('cm', 'centimeter'), ('pс', 'piece')], default='kg', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='price',
            field=models.FloatField(default=0, verbose_name='Ориентировочная цена в руб. за единицу измерения'),
        ),
    ]
