# Generated by Django 4.1.7 on 2023-03-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsite', '0002_ingredients_measure_alter_ingredients_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(related_name='dishes', to='foodsite.ingredients', verbose_name='Какие ингредиенты используются'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='measure',
            field=models.CharField(choices=[('kg', 'kilo'), ('g', 'gramm'), ('cm', 'centimeter'), ('pс', 'piece')], max_length=3, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Является ли менеджером?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Оплачена премиум подписка?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='some_user', max_length=250, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=12, verbose_name='Пароль'),
        ),
    ]
