# Generated by Django 4.1.7 on 2023-03-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsite', '0003_alter_dish_image_alter_dish_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dish',
            old_name='dislike',
            new_name='dislikes',
        ),
        migrations.AlterField(
            model_name='user',
            name='not_used_ingr',
            field=models.ManyToManyField(blank=True, related_name='not_for_users', to='foodsite.ingredients', verbose_name='Блюда с какими ингредиентами не предлагать'),
        ),
    ]
