# Generated by Django 4.1.7 on 2023-03-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodsite', '0005_alter_user_managers_rename_name_user_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_manager',
            new_name='is_staff',
        ),
    ]
