# Generated by Django 4.1.7 on 2023-03-16 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodsite', '0006_rename_is_manager_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.BooleanField(verbose_name='Включен ли завтрак?')),
                ('lunch', models.BooleanField(verbose_name='Включен ли обед?')),
                ('dinner', models.BooleanField(verbose_name='Включен ли ужин?')),
                ('dessert', models.BooleanField(verbose_name='Включен ли десерт?')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='price',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='user',
            name='not_used_ingr',
        ),
        migrations.AddField(
            model_name='dish',
            name='group',
            field=models.CharField(choices=[('mt', 'meet'), ('fs', 'fish'), ('vt', 'vegetable'), ('fr', 'fruit'), ('vegt', 'vegetarian'), ('veg', 'vegan'), ('gf', 'gluten_free'), ('eco', 'eco'), ('gf', 'gluten_free'), ('eco', 'eco')], default='meet', max_length=4, verbose_name='Предпочитаемые блюда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.FloatField(default=0, verbose_name='Ориентировочная цена в руб. за блюдо'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_dishes',
            field=models.CharField(choices=[('mt', 'meet'), ('fs', 'fish'), ('vt', 'vegetable'), ('fr', 'fruit'), ('vegt', 'vegetarian'), ('veg', 'vegan'), ('gf', 'gluten_free'), ('eco', 'eco'), ('gf', 'gluten_free'), ('eco', 'eco')], default='meet', max_length=4, verbose_name='Предпочитаемые блюда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tarif',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='foodsite.tarif', verbose_name='Оплаченный тариф'),
        ),
    ]
