# Generated by Django 4.1.7 on 2023-03-16 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodsite', '0007_tarif_remove_ingredients_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tarif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='foodsite.tarif', verbose_name='Оплаченный тариф'),
        ),
    ]
