# Generated by Django 4.1.7 on 2023-03-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsite', '0008_alter_user_tarif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='group',
        ),
        migrations.AddField(
            model_name='dish',
            name='group_food',
            field=models.CharField(blank=True, choices=[('mt', 'meet'), ('fs', 'fish'), ('vt', 'vegetable'), ('fr', 'fruit'), ('vegt', 'vegetarian'), ('veg', 'vegan'), ('gf', 'gluten_free'), ('eco', 'eco')], max_length=4, null=True, verbose_name='Входит в группу'),
        ),
        migrations.AddField(
            model_name='dish',
            name='in_menu',
            field=models.CharField(blank=True, choices=[('cl', 'Классическое'), ('lc', 'Низкоуглеводное'), ('vg', 'Вегетарианское'), ('kt', 'Кето')], max_length=2, null=True, verbose_name='Входит в меню'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='allergen',
            field=models.CharField(blank=True, choices=[('fs', 'Рыба и морепродукты'), ('mt', 'Мясо'), ('cl', 'Зерновые'), ('hn', 'Продукты пчеловодства'), ('nt', 'Орехи и бобовые'), ('mk', 'Молочные продукты')], max_length=2, null=True, verbose_name='Входит в группу алергенов'),
        ),
        migrations.AddField(
            model_name='user',
            name='allergy',
            field=models.CharField(blank=True, choices=[('fs', 'Рыба и морепродукты'), ('mt', 'Мясо'), ('cl', 'Зерновые'), ('hn', 'Продукты пчеловодства'), ('nt', 'Орехи и бобовые'), ('mk', 'Молочные продукты')], max_length=2, null=True, verbose_name='Алергия на:'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_dishes',
            field=models.CharField(blank=True, choices=[('mt', 'meet'), ('fs', 'fish'), ('vt', 'vegetable'), ('fr', 'fruit'), ('vegt', 'vegetarian'), ('veg', 'vegan'), ('gf', 'gluten_free'), ('eco', 'eco')], max_length=4, null=True, verbose_name='Предпочитаемые блюда'),
        ),
    ]
