# Generated by Django 4.1.7 on 2023-03-17 18:11

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foodsite', '0010_user_preferred_menu_alter_dish_group_food_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allergy',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_menu',
        ),
        migrations.AddField(
            model_name='tarif',
            name='allergy',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fs', 'Рыба и морепродукты'), ('mt', 'Мясо'), ('cl', 'Зерновые'), ('hn', 'Продукты пчеловодства'), ('nt', 'Орехи и бобовые'), ('mk', 'Молочные продукты')], max_length=2, null=True, verbose_name='Алергия на:'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='duration',
            field=models.CharField(choices=[('1', '1 месяц'), ('3', '3 месяца'), ('6', '6 месяцев'), ('12', '12 месяцев')], default='1 месяц', max_length=2, verbose_name='Длительность подписки'),
        ),
        migrations.AddField(
            model_name='tarif',
            name='preferred_menu',
            field=models.CharField(blank=True, choices=[('cl', 'Классическое'), ('lc', 'Низкоуглеводное'), ('vg', 'Вегетарианское'), ('kt', 'Кето')], max_length=2, null=True, verbose_name='Предпочитаемое меню'),
        ),
    ]
