# Generated by Django 4.1.7 on 2023-03-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsite', '0011_remove_user_allergy_remove_user_preferred_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarif',
            name='persons',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество персон'),
        ),
    ]
