# Generated by Django 4.1.7 on 2023-03-18 13:06

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foodsite', '0013_alter_dish_options_alter_ingredients_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='calories',
            field=models.FloatField(default=1000, verbose_name='Калорийность ккал'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='group_food',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('mt', 'Мясо'), ('fs', 'Рыба'), ('vt', 'Овощи'), ('fr', 'Фрукты'), ('vegt', 'Вегетарианское'), ('veg', 'Веганское'), ('gf', 'Без глютена'), ('eco', 'ЭКО')], max_length=15, null=True, verbose_name='Входит в группу'),
        ),
    ]
