# Generated by Django 4.1.7 on 2023-03-19 23:19

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foodsite', '0014_dish_calories_alter_dish_group_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='recipe',
            field=models.TextField(blank=True, verbose_name='Рецепт блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='in_menu',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cl', 'Классическое'), ('lc', 'Низкоуглеводное'), ('vg', 'Вегетарианское'), ('kt', 'Кето')], max_length=11, null=True, verbose_name='Входит в меню'),
        ),
    ]
