# Generated by Django 4.1.7 on 2023-03-20 18:40

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foodsite', '0015_dish_recipe_alter_dish_in_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='allergy',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fs', 'Рыба и морепродукты'), ('mt', 'Мясо'), ('cl', 'Зерновые'), ('hn', 'Продукты пчеловодства'), ('nt', 'Орехи и бобовые'), ('mk', 'Молочные продукты')], default='', max_length=12, null=True, verbose_name='Алергия на:'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='breakfast',
            field=models.BooleanField(default=True, verbose_name='Включен ли завтрак?'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='dessert',
            field=models.BooleanField(default=True, verbose_name='Включен ли десерт?'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='dinner',
            field=models.BooleanField(default=True, verbose_name='Включен ли ужин?'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='duration',
            field=models.CharField(choices=[('1', '1 месяц'), ('3', '3 месяца'), ('6', '6 месяцев'), ('12', '12 месяцев')], default='1', max_length=2, verbose_name='Длительность подписки'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='lunch',
            field=models.BooleanField(default=True, verbose_name='Включен ли обед?'),
        ),
        migrations.AlterField(
            model_name='tarif',
            name='preferred_menu',
            field=models.CharField(blank=True, choices=[('cl', 'Классическое'), ('lc', 'Низкоуглеводное'), ('vg', 'Вегетарианское'), ('kt', 'Кето')], default='cl', max_length=2, null=True, verbose_name='Предпочитаемое меню'),
        ),
    ]
