# Generated by Django 4.1.7 on 2023-03-20 18:47

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foodsite', '0016_alter_tarif_allergy_alter_tarif_breakfast_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarif',
            name='allergy',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('fs', 'Рыба и морепродукты'), ('mt', 'Мясо'), ('cl', 'Зерновые'), ('hn', 'Продукты пчеловодства'), ('nt', 'Орехи и бобовые'), ('mk', 'Молочные продукты')], default='cl', max_length=12, verbose_name='Алергия на:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarif',
            name='preferred_menu',
            field=models.CharField(choices=[('cl', 'Классическое'), ('lc', 'Низкоуглеводное'), ('vg', 'Вегетарианское'), ('kt', 'Кето')], default='cl', max_length=2, verbose_name='Предпочитаемое меню'),
        ),
    ]
